#!/bin/bash
# simple aur helper, basic, minimal, no fuss.
# JaydenDev, MIT, 2022
mkdir -p $HOME/.local/share/saurh

if [[ $1 == "v" ]]
then
	echo "saurh v0.1.0-edge"
	exit 0
fi

if [[ -z $1 ]]
then
	echo "saurh
---------------
install, install
remove, remove"
exit 1
fi

if [ $1 == "install" ];
then 
	if [[ -z $2 ]]
	then
		echo "please provide a second argument (package)."
		exit 1
	fi
	rm -rf $HOME/.cache/saurh/$2
	git clone https://aur.archlinux.org/$2 $HOME/.cache/saurh/$2
	cd $HOME/.cache/saurh/$2
	file="$HOME/.cache/saurh/$2/PKGBUILD"
	echo $file
	if [ ! -f "$file" ]; then
		echo "ERR: Package does not exist in AUR"
		exit
	else
		echo "SUCCESS: Package found"
	fi
	echo "PKGBUILD Contents"
	echo ----------------------------------------
	cat $HOME/.cache/saurh/$2/PKGBUILD
       	echo ----------------------------------------
	read -p "Would you like to install $2? [y/n] " yn
	case $yn in
		y ) echo ok, we will proceed;;
		n ) exit 1;;
		* ) echo invalid response;
			exit 1;;
	esac
	makepkg -si || echo "There was a problem when installing this package, drop into ~/.local/share/saurh/package and try to makepkg or fix issues yourself."
fi

if [ $1 == "uninstall" ];
then	command -v pacman >&/dev/null || exit 1
	if [[ -v $2 ]]
	then
		echo "please provide a second argument (package)."
	fi
	sudo pacman -R $2 || echo "command failed, is the package not installed?"
fi

if [ $1 == "yay-migrate" ];
then
	echo Migrating build files from yay cache...
	file="$HOME/.cache/yay/"
	if [ ! -d "$file" ]; then
		echo "ERR: No yay cache to migrate"
		exit
	fi
	cp -r $HOME/.cache/yay/* $HOME/.cache/saurh/
fi


if [[ $1 == "update" ]]
then
	find $HOME/.cache/saurh -mindepth 1 -maxdepth 1 -type d | while read pkg; do
	cd $pkg
	if [[ `git status --porcelain --untracked-files=no` ]]; then
  		echo Updates available for package $pkg
	else
  		echo No updates available for package $pkg
		exit
fi
		makepkg -si || echo "ERR: Failed to install package $pkg"
	done
fi

